// Generated by CoffeeScript 1.6.3
(function() {
  define(['./nobj', './data'], function(nobj, data) {
    var global;
    global = this;
    return {
      afterNewLoad: function(collection, formQuery) {
        return function() {
          var form;
          form = $(formQuery);
          return form.submit(function() {
            nobj.post(form, collection).done(function() {
              return alert('New item added');
            }).fail(function() {
              return alert('Error while adding item');
            });
            return false;
          });
        };
      },
      afterEditLoad: function(collection, formQuery) {
        return function() {
          var form;
          form = $(formQuery);
          nobj.obj2form(global.nobj.collections[collection].current, form);
          return form.submit(function() {
            nobj.put(form, collection).done(function() {
              return alert('Item Saved');
            }).fail(function() {
              return alert('Error while updating item');
            });
            return false;
          });
        };
      },
      afterListLoad: function(collection, tableQuery) {
        var fillTable, registerActions;
        registerActions = function(row, item) {
          $('a.editLink', row).click(function() {
            return global.nobj.collections[collection].current = item;
          });
          return $('a.delLink', row).click(function() {
            data["delete"](collection, item._id).done(function(result) {
              alert('Item deleted: ' + result.result);
              return row.remove();
            }).fail(function(err) {
              return alert('Error: ' + err);
            });
            return false;
          });
        };
        fillTable = function() {
          return data.get(collection).done(function(result) {
            return nobj.fillTable(result.items, $(tableQuery), function(item, row) {
              var actions;
              actions = '<a class="editLink" href="#' + collection + '/edit">Edit</a>';
              actions += ' / <a class="delLink" href="">Delete</a>';
              $('td:last', row).append(actions);
              return registerActions(row, item);
            });
          }).fail(function(err) {
            return alert('Error: ' + err);
          });
        };
        return function() {
          return fillTable();
        };
      }
    };
  });

}).call(this);
