// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var nav;
    nav = {
      oldViewId: '',
      defaultViewId: '',
      loadView: function(viewId) {
        var oldController, url, _ref,
          _this = this;
        oldController = this.controller;
        this.controller = typeof this.getController === "function" ? this.getController(viewId) : void 0;
        if (oldController != null) {
          if (typeof oldController.beforeUnload === "function") {
            oldController.beforeUnload(this.oldViewId);
          }
        }
        if ((_ref = this.controller) != null) {
          if (typeof _ref.beforeLoad === "function") {
            _ref.beforeLoad(viewId);
          }
        }
        url = viewId + '.html';
        return $('#view').load(url, function() {
          var _ref1;
          console.log('Loaded ' + url);
          if (oldController != null) {
            if (typeof oldController.afterUnload === "function") {
              oldController.afterUnload(_this.oldViewId);
            }
          }
          if ((_ref1 = _this.controller) != null) {
            if (typeof _ref1.afterLoad === "function") {
              _ref1.afterLoad(viewId);
            }
          }
          return _this.oldViewId = viewId;
        });
      }
    };
    window.onhashchange = function() {
      var viewId;
      console.log('Hash changed to ' + location.hash);
      if (location.hash.length <= 0) {
        viewId = nav.defaultViewId;
      } else {
        viewId = location.hash.substring(1);
      }
      return nav.loadView(viewId);
    };
    return nav;
  });

}).call(this);
