// Generated by CoffeeScript 1.6.3
(function() {
  define(['data', 'nobj'], function(data, nobj) {
    var afterBooksLoad, afterEditLoad, afterNewLoad, bookSpec, global;
    global = this;
    afterBooksLoad = function() {
      var fillTable, registerActions;
      registerActions = function(row, book) {
        $('a.editLink', row).click(function() {
          return global.books.current = book;
        });
        return $('a.delLink', row).click(function() {
          data["delete"]('books', book._id).done(function(result) {
            alert('Book deleted: ' + result);
            return row.remove();
          }).fail(function(err) {
            return alert('Error: ' + err);
          });
          return false;
        });
      };
      fillTable = function() {
        return data.get('books').done(function(result) {
          var book, items, newRow, newRowElement, rows, _i, _len, _results;
          items = result.items;
          rows = $('#books tbody');
          _results = [];
          for (_i = 0, _len = items.length; _i < _len; _i++) {
            book = items[_i];
            newRow = '<tr><td>' + book.title + '</td>';
            newRow += '<td>' + book.author + '</td>';
            newRow += '<td><a class=\'editLink\' href=\'#edit\'>Edit</a>';
            newRow += ' / <a class=\'delLink\' href=\'\'>Delete</a></td></tr>';
            newRowElement = $(newRow);
            registerActions(newRowElement, book);
            _results.push(rows.append(newRowElement));
          }
          return _results;
        }).fail(function(err) {
          return alert('Error: ' + err);
        });
      };
      return fillTable();
    };
    afterEditLoad = function() {
      var form;
      form = $('#book_edit');
      nobj.obj2form(global.books.current, form, bookSpec);
      return form.submit(function() {
        nobj.put(form, bookSpec).done(function() {
          return alert('Data Saved');
        }).fail(function() {
          return alert('Error while saving data');
        });
        return false;
      });
    };
    afterNewLoad = function() {
      var form;
      form = $('#book_new');
      return form.submit(function() {
        nobj.post(form, bookSpec).done(function() {
          return alert('New book added');
        }).fail(function() {
          return alert('Error while saving data');
        });
        return false;
      });
    };
    bookSpec = {
      collection: 'books',
      fields: [
        {
          field: 'title'
        }, {
          field: 'author'
        }
      ]
    };
    return {
      books: {
        afterLoad: afterBooksLoad
      },
      edit: {
        afterLoad: afterEditLoad
      },
      "new": {
        afterLoad: afterNewLoad
      }
    };
  });

}).call(this);
