// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    return {
      books: {
        afterLoad: function() {
          return console.log('After load books');
        }
      },
      edit: {
        afterLoad: function() {
          return console.log('After load edit');
        }
      },
      "new": {
        afterLoad: function() {
          return console.log('After load new');
        }
      }
    };
  });

}).call(this);
