// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var ajax;
    ajax = function(collection, method, data) {
      var deferred;
      deferred = $.Deferred();
      data = data || {};
      data._method = method;
      $.ajax({
        type: 'POST',
        url: "/data/" + collection,
        data: data
      }).done(function(result) {
        if (result.err) {
          return deferred.reject(result.err);
        } else {
          return deferred.resolve(result);
        }
      }).fail(function(result) {
        return deferred.reject(result);
      });
      return deferred.promise();
    };
    return {
      get: function(collection) {
        return ajax(collection, 'get');
      },
      put: function(collection, putData) {
        return ajax(collection, 'put', putData);
      },
      post: function(collection, postData) {
        return ajax(collection, 'post', postData);
      },
      "delete": function(collection, oid) {
        var delData;
        delData = {
          _id: oid
        };
        return ajax(collection, 'delete', delData);
      }
    };
  });

}).call(this);
