// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    return {
      get: function(collection, cb) {
        return $.ajax({
          type: 'POST',
          url: "/data/" + collection,
          data: {
            _method: 'get'
          }
        }).done(function(result) {
          if (result.err) {
            return alert(result.err);
          } else {
            return cb(result.items);
          }
        });
      },
      put: function(collection, putData, cb) {
        putData._method = 'put';
        return $.ajax({
          type: 'POST',
          url: "/data/" + collection,
          data: putData
        }).done(function(result) {
          return cb(result);
        });
      }
    };
  });

}).call(this);
