// Generated by CoffeeScript 1.6.3
(function() {
  require(['nav'], function(nav) {
    if (!window.console) {
      window.console = {
        log: function() {}
      };
    }
    nav.loadView("books.html");
    return window.books = {};
  });

}).call(this);
