// Generated by CoffeeScript 1.6.3
(function() {
  require(['nav', 'controllers'], function(nav, controllers) {
    if (!window.console) {
      window.console = {
        log: function() {}
      };
    }
    window.books = {};
    nav.getController = function(viewId) {
      return controllers[viewId];
    };
    nav.defaultViewId = 'books';
    return nav.loadView(nav.defaultViewId);
  });

}).call(this);
