// Generated by CoffeeScript 1.6.3
(function() {
  require(['nobj/nav', 'nobj/crudControllers'], function(nav, crudControllers) {
    if (!window.console) {
      window.console = {
        log: function() {}
      };
    }
    crudControllers.addCollection('books');
    nav.getController = crudControllers.getController;
    nav.defaultViewId = 'collections';
    return nav.loadView(nav.defaultViewId);
  });

}).call(this);
