// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var nav;
    nav = {
      loadView: function(url) {
        return $("#view").load(url, function() {
          return console.log("Loaded " + url);
        });
      }
    };
    window.onhashchange = function() {
      var url;
      console.log("Hash changed to " + location.hash);
      if (location.hash.length <= 0) {
        url = "books.html";
      } else {
        url = location.hash.substring(1) + ".html";
      }
      return nav.loadView(url);
    };
    return nav;
  });

}).call(this);
