// Generated by CoffeeScript 1.6.3
(function() {
  define(['data'], function(data) {
    return {
      obj2form: function(obj, form) {
        var input, jqInput, value, _i, _len, _ref, _results;
        _ref = $('[name]', form);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          input = _ref[_i];
          jqInput = $(input);
          value = obj[jqInput.attr('name')];
          if (value) {
            _results.push(jqInput.val(value));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      },
      post: function(form, collection) {
        return data.post(collection, form.serialize());
      },
      put: function(form, collection) {
        var putData;
        putData = form.serialize();
        return data.put(collection, putData);
      }
    };
  });

}).call(this);
