// Generated by CoffeeScript 1.6.3
(function() {
  define(['data'], function(data) {
    var capitalize, getFormInput;
    capitalize = function(str) {
      return str.substring(0, 1).toUppercase() + str.substring(1);
    };
    getFormInput = function(form, field) {
      return $("[name=" + field + "]", form);
    };
    return {
      obj2form: function(obj, form, spec) {
        var fieldSpec, _i, _len, _ref, _ref1, _ref2;
        _ref = spec.fields;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          fieldSpec = _ref[_i];
          if ((_ref1 = getFormInput(form, fieldSpec.field)) != null) {
            _ref1.val(obj[fieldSpec.field]);
          }
        }
        return (_ref2 = getFormInput(form, '_id')) != null ? _ref2.val(obj._id) : void 0;
      },
      post: function(form, collection) {
        return data.post(collection, form.serialize());
      },
      put: function(form, collection) {
        var putData;
        putData = form.serialize();
        return data.put(collection, putData);
      }
    };
  });

}).call(this);
