// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var BookListController;
    BookListController = (function() {
      function BookListController(collection, query) {
        this.collection = collection;
        this.query = query;
      }

      BookListController.prototype.afterLoad = function() {
        return console.log('User edit after load');
      };

      return BookListController;

    })();
    return {
      BookListController: BookListController
    };
  });

}).call(this);
